"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-07-21 02:33:57.009777
"""

from alembic import op
import sqlalchemy as sa


revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "family",
        sa.Column("id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "judge_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("judge_model", sa.String(), nullable=False),
        sa.Column("judge_reasoning", sa.String(), nullable=False),
        sa.Column("prompt_hash", sa.String(), nullable=False),
        sa.Column("prompt_text", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("judge_model", "judge_reasoning", "prompt_hash"),
    )
    op.create_table(
        "model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("inspect_model", sa.String(), nullable=True),
        sa.Column("reasoning_effort", sa.String(), nullable=True),
        sa.Column("display", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "question",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("first_seen_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("origin", sa.String(), nullable=False),
        sa.Column("source_path", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("git_commit", sa.String(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("cost", sa.JSON(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_path"),
    )
    op.create_table(
        "family_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("family_id", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("prompt", sa.String(), nullable=False),
        sa.Column("scalar", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["family.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("family_id", "content_hash"),
    )
    op.create_table(
        "gen_batch",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("digest", sa.String(), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=True),
        sa.Column("max_tokens", sa.Integer(), nullable=True),
        sa.Column("n_requested", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("git_commit", sa.String(), nullable=True),
        sa.Column("inspect_eval_id", sa.String(), nullable=True),
        sa.Column("log_path", sa.String(), nullable=True),
        sa.Column("log_sha256", sa.String(), nullable=True),
        sa.Column("in_tok", sa.Integer(), nullable=True),
        sa.Column("out_tok", sa.Integer(), nullable=True),
        sa.Column("est_dollars", sa.Float(), nullable=True),
        sa.Column("origin", sa.String(), nullable=False),
        sa.Column("source_path", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("digest"),
    )
    op.create_table(
        "question_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("prompt", sa.String(), nullable=False),
        sa.Column("system", sa.String(), nullable=True),
        sa.Column("group_name", sa.String(), nullable=False),
        sa.Column("bucket", sa.String(), nullable=True),
        sa.Column("family_id", sa.String(), nullable=True),
        sa.Column("variant", sa.String(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["family.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("question_id", "content_hash"),
    )
    op.create_table(
        "bundle",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("digest", sa.String(), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("question_version_id", sa.Integer(), nullable=False),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["model.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_version_id"],
            ["question_version.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("digest"),
    )
    with op.batch_alter_table("bundle", schema=None) as batch_op:
        batch_op.create_index("ix_bundle_model", ["model_id"], unique=False)
        batch_op.create_index("ix_bundle_qv", ["question_version_id"], unique=False)

    op.create_table(
        "family_analysis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("digest", sa.String(), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("family_version_id", sa.Integer(), nullable=True),
        sa.Column("judge_config_id", sa.Integer(), nullable=True),
        sa.Column("rep_label", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("source_path", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["family_version_id"],
            ["family_version.id"],
        ),
        sa.ForeignKeyConstraint(
            ["judge_config_id"],
            ["judge_config.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("digest"),
    )
    op.create_table(
        "response",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("question_version_id", sa.Integer(), nullable=False),
        sa.Column("sample_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["gen_batch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_version_id"],
            ["question_version.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", "question_version_id", "sample_index"),
    )
    with op.batch_alter_table("response", schema=None) as batch_op:
        batch_op.create_index("ix_response_qv", ["question_version_id"], unique=False)

    op.create_table(
        "bundle_response",
        sa.Column("bundle_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("response_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bundle_id"],
            ["bundle.id"],
        ),
        sa.ForeignKeyConstraint(
            ["response_id"],
            ["response.id"],
        ),
        sa.PrimaryKeyConstraint("bundle_id", "position"),
        sa.UniqueConstraint("bundle_id", "response_id"),
    )
    op.create_table(
        "clustering",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bundle_id", sa.Integer(), nullable=False),
        sa.Column("backend", sa.String(), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("n_clusters", sa.Integer(), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bundle_id"],
            ["bundle.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bundle_id", "backend", "threshold"),
    )
    op.create_table(
        "embedding",
        sa.Column("response_id", sa.Integer(), nullable=False),
        sa.Column("backend", sa.String(), nullable=False),
        sa.Column("dim", sa.Integer(), nullable=False),
        sa.Column("vec", sa.LargeBinary(), nullable=False),
        sa.ForeignKeyConstraint(
            ["response_id"],
            ["response.id"],
        ),
        sa.PrimaryKeyConstraint("response_id", "backend"),
    )
    op.create_table(
        "judgment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("digest", sa.String(), nullable=False),
        sa.Column("bundle_id", sa.Integer(), nullable=False),
        sa.Column("judge_config_id", sa.Integer(), nullable=False),
        sa.Column("rep_label", sa.String(), nullable=False),
        sa.Column("contradiction", sa.Boolean(), nullable=True),
        sa.Column("n_groups", sa.Integer(), nullable=True),
        sa.Column("verdict", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.Column("git_commit", sa.String(), nullable=True),
        sa.Column("log_path", sa.String(), nullable=True),
        sa.Column("origin", sa.String(), nullable=False),
        sa.Column("source_path", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bundle_id"],
            ["bundle.id"],
        ),
        sa.ForeignKeyConstraint(
            ["judge_config_id"],
            ["judge_config.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("digest"),
    )
    with op.batch_alter_table("judgment", schema=None) as batch_op:
        batch_op.create_index("ix_judgment_bundle", ["bundle_id"], unique=False)

    op.create_table(
        "run_bundle",
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("bundle_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bundle_id"],
            ["bundle.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "bundle_id"),
    )
    op.create_table(
        "run_family_analysis",
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("family_analysis_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_analysis_id"],
            ["family_analysis.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "family_analysis_id"),
    )
    op.create_table(
        "bundle_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("digest", sa.String(), nullable=False),
        sa.Column("bundle_id", sa.Integer(), nullable=False),
        sa.Column("judgment_id", sa.Integer(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bundle_id"],
            ["bundle.id"],
        ),
        sa.ForeignKeyConstraint(
            ["judgment_id"],
            ["judgment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("digest"),
    )
    with op.batch_alter_table("bundle_metrics", schema=None) as batch_op:
        batch_op.create_index("ix_metrics_bundle", ["bundle_id"], unique=False)

    op.create_table(
        "run_judgment",
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("judgment_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["judgment_id"],
            ["judgment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "judgment_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("run_judgment")
    with op.batch_alter_table("bundle_metrics", schema=None) as batch_op:
        batch_op.drop_index("ix_metrics_bundle")

    op.drop_table("bundle_metrics")
    op.drop_table("run_family_analysis")
    op.drop_table("run_bundle")
    with op.batch_alter_table("judgment", schema=None) as batch_op:
        batch_op.drop_index("ix_judgment_bundle")

    op.drop_table("judgment")
    op.drop_table("embedding")
    op.drop_table("clustering")
    op.drop_table("bundle_response")
    with op.batch_alter_table("response", schema=None) as batch_op:
        batch_op.drop_index("ix_response_qv")

    op.drop_table("response")
    op.drop_table("family_analysis")
    with op.batch_alter_table("bundle", schema=None) as batch_op:
        batch_op.drop_index("ix_bundle_qv")
        batch_op.drop_index("ix_bundle_model")

    op.drop_table("bundle")
    op.drop_table("question_version")
    op.drop_table("gen_batch")
    op.drop_table("family_version")
    op.drop_table("run")
    op.drop_table("question")
    op.drop_table("model")
    op.drop_table("judge_config")
    op.drop_table("family")
    # ### end Alembic commands ###
